//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.InventoryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopLog
    {
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string InUserID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<bool> UseChk { get; set; }
        public string AreaCode { get; set; }
        public string Password { get; set; }
        public Nullable<bool> LoginSuccessChk { get; set; }
    }
}
